#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-hexView
Version  : 0.3.4
Release  : 28
URL      : https://cran.r-project.org/src/contrib/hexView_0.3-4.tar.gz
Source0  : https://cran.r-project.org/src/contrib/hexView_0.3-4.tar.gz
Summary  : Viewing Binary Files
Group    : Development/Tools
License  : GPL-2.0
BuildRequires : buildreq-R

%description
# hexview
The 'hexView' package for R

%prep
%setup -q -c -n hexView
cd %{_builddir}/hexView

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641032214

%install
export SOURCE_DATE_EPOCH=1641032214
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library hexView
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library hexView
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library hexView
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc hexView || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/hexView/DESCRIPTION
/usr/lib64/R/library/hexView/INDEX
/usr/lib64/R/library/hexView/Meta/Rd.rds
/usr/lib64/R/library/hexView/Meta/features.rds
/usr/lib64/R/library/hexView/Meta/hsearch.rds
/usr/lib64/R/library/hexView/Meta/links.rds
/usr/lib64/R/library/hexView/Meta/nsInfo.rds
/usr/lib64/R/library/hexView/Meta/package.rds
/usr/lib64/R/library/hexView/NAMESPACE
/usr/lib64/R/library/hexView/NEWS.Rd
/usr/lib64/R/library/hexView/R/hexView
/usr/lib64/R/library/hexView/R/hexView.rdb
/usr/lib64/R/library/hexView/R/hexView.rdx
/usr/lib64/R/library/hexView/files/data4-1.txt
/usr/lib64/R/library/hexView/files/data4-1.wf1
/usr/lib64/R/library/hexView/files/rawTest.XDRint
/usr/lib64/R/library/hexView/files/rawTest.XDRreal
/usr/lib64/R/library/hexView/files/rawTest.bin
/usr/lib64/R/library/hexView/files/rawTest.int
/usr/lib64/R/library/hexView/files/rawTest.real
/usr/lib64/R/library/hexView/files/rawTest.txt
/usr/lib64/R/library/hexView/files/rawTest.unicode
/usr/lib64/R/library/hexView/files/rawTest.unicode.txt
/usr/lib64/R/library/hexView/help/AnIndex
/usr/lib64/R/library/hexView/help/aliases.rds
/usr/lib64/R/library/hexView/help/hexView.rdb
/usr/lib64/R/library/hexView/help/hexView.rdx
/usr/lib64/R/library/hexView/help/paths.rds
/usr/lib64/R/library/hexView/html/00Index.html
/usr/lib64/R/library/hexView/html/R.css
